version: '3.4'

services:
  
  frontend:
    image: pizzafrontend
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - backendUrl=http://backend
      - ASPNETCORE_HTTPS_PORT=6001      
    ports:
      - "6001:443"
      - "6000:80"
    volumes:
      - ${HOME}/certs/:/https
    depends_on:
      - backend
  backend:
    image: pizzabackend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_HTTPS_PORT=5001      
    ports:
      - "5001:443"
      - "5000:80"
    volumes:
      - ${HOME}/certs/:/https
      